### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by JeongHunMoon**
What is it? 
- It is about distribution for ver 1.

### CODE REVIEW

**Comment by JeongHunMoon** [comment]
I would like to distribute this branch for ver 1. Could you please review our source code

**Comment by thisis-joe** [comment]
> I would like to distribute this branch for ver 1. Could you please review our source code

Hello. Is it version1 or 0.0.1 SNAPSHOT? could you please check it one more time? and i think we need to refactoring more several times..

**Comment by JeongHunMoon** [comment]
> > I would like to distribute this branch for ver 1. Could you please review our source code
> 
> Hello. Is it version1 or 0.0.1 SNAPSHOT? could you please check it one more time? and i think we need to refactoring more several times..


Sorry. This is for snapshot 0.0.1. The final deployment will require creating a PR again. This is for test deployment. I will merge miain. Since I work night shift, please distribute 0.0.1.

**Comment by thisis-joe** [comment]
> > > I would like to distribute this branch for ver 1. Could you please review our source code
> > 
> > 
> > Hello. Is it version1 or 0.0.1 SNAPSHOT? could you please check it one more time? and i think we need to refactoring more several times..
> 
> �Sorry. This is for snapshot 0.0.1. The final deployment will require creating a PR again. This is for test deployment. I will merge miain. Since I work night shift, please distribute 0.0.1.

Sure. Just merge to main branch plz. I can distribute to our Ubuntu Server.

**Pull request merged**
